title = "Verena Ortlieb"
languageCode = "en-us"
baseurl = "https://www.verenaortlieb.de/"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
    name = "Verena Ortlieb"

[blackfriday]
   hrefTargetBlank = true

[[menu.main]]
    name = "Ich"
    identifier = "ich"
    url = "/ich/"
    weight = 110

[[menu.main]]
    name = "Du"
    identifier = "du"
    url = "/du/"
    weight = 120

[[menu.main]]
    name = "Coaching"
    identifier = "coaching"
    url = "/coaching/"
    weight = 130

[[menu.main]]
    name = "Lob"
    identifier = "lob"
    url = "/lob/"
    weight = 140

[[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/blog/"
    weight = 150

[[menu.main]]
    name = "Kontakt"
    identifier = "kontakt"
    url = "/kontakt/"
    weight = 160