title = "Verena Ortlieb"
languageCode = "de-de"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

baseurl = "https://www.verenaortlieb.de/"


[author]
  name = "Verena Ortlieb"

[blackfriday]
  hrefTargetBlank = true

[[menu.main]]
  name = "Blog"
  identifier = "blog"
  url = "/blog/"
  weight = 5
