title = "Verena Ortlieb"
languageCode = "en-us"
baseurl = "https://www.verenaortlieb.de/"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
    name = "Verena Ortlieb"

[blackfriday]
   hrefTargetBlank = true

# [[menu.main]]
#     name = "Design"
#     identifier = "design"
#     url = "/work/"
#     weight = -110

# [[menu.main]]
#     name = "Websites"
#     identifier = "design"
#     url = "/websites/"
#     weight = -100

# [[menu.main]]
#     name = "Fun Stuff"
#     identifier = "design"
#     url = "/funstuff/"
#     weight = -90
