title = "Verena"
languageCode = "en-us"
baseurl = "https://www.verenaortlieb.de/"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
    name = "Verena Ortlieb"

[blackfriday]
   hrefTargetBlank = true

[[menu.main]]
    name = "Design"
    identifier = "design"
    url = "/design/"
    weight = -110

[[menu.main]]
    name = "Websites"
    identifier = "websites"
    url = "/websites/"
    weight = -100

[[menu.main]]
    name = "Fun Stuff"
    identifier = "funstuff"
    url = "/funstuff/"
    weight = -90
