baseURL = "https://www.verenaortlieb.de/"
languageCode = "de-de"
title = "Verena Ortlieb"

[author]
    name = "Verena Ortlieb"

[blackfriday]
   hrefTargetBlank = true

# [[menu.main]]
#     name = "Blog"
#     identifier = "blog"
#     url = "/blog/"
#     weight = 150